### ISSUE TITLE
iTrace-Core does not recognize Tobii Pro Fusion

### ISSUE THREAD

**Issue by pdreiter** [iTrace-Dev/iTrace-Core#185]
Although the Tobii Pro Fusion's `EyeChip` USB device is listed in Device Manager, iTrace-Core does not identify any tracker other than `Mouse`.  iTrace Documentation indicates that Tobii Pro devices are supported, but specifically verified/tested models are not indicated. 
Additionally, the documentation provides no information on how to debug or address issues like this.
Please advise!

**Comment by pdreiter** [comment]
It looks like the issue was on my end, after updating the drivers via the Tobii Pro Eye Tracker Manager, it looks like it's now recognizing the Tobii Pro Fusion device.

**Comment by KangilPark** [comment]
Solution to problem has been found.
