### ISSUE TITLE
Selecting Recording Monitor

### ISSUE THREAD

**Issue by dtg3** [iTrace-Dev/iTrace-Core#40]
Presently core should use the screen dimensions from the **primary monitor** when calculating gaze positions with respect to the screen size.

This should be a configurable option when setting up a session.

This will need to be done a different way now that we have migrated to C#.
~~We can get the desktop with this:~~
~~``` QApplication::desktop()```~~
~~and then get additional information about the displays using [these functions](http://doc.qt.io/qt-5/qdesktopwidget.html)~~

**Comment by KangilPark** [comment]
Feature to select recording monitor is implemented under settings.
